"""VASP file parser using pymatgen with fallback regex."""
import re
import logging
from typing import Any

logger = logging.getLogger(__name__)

class INCARParser:
    """Parse and serialize INCAR files."""

    @staticmethod
    def parse(content: str) -> dict[str, Any]:
        params: dict[str, Any] = {}
        lines = content.split("\n")
        for line in lines:
            line = line.split("#")[0].split("!")[0].strip()
            if not line or "=" not in line:
                continue
            key, _, value = line.partition("=")
            key = key.strip()
            value = value.strip()
            if not key:
                continue
            if value.upper() in (".TRUE.", "T", ".FALSE.", "F"):
                params[key] = value.upper() in (".TRUE.", "T")
            elif re.match(r'^[\d.eE+\-\s]+$', value):
                parts = value.split()
                if len(parts) == 1:
                    try:
                        params[key] = int(parts[0])
                    except ValueError:
                        try:
                            params[key] = float(parts[0])
                        except ValueError:
                            params[key] = value
                else:
                    try:
                        params[key] = [float(p) for p in parts]
                    except ValueError:
                        params[key] = value
            else:
                params[key] = value
        return params

    @staticmethod
    def to_string(params: dict[str, Any]) -> str:
        lines = []
        for tag, value in sorted(params.items()):
            if isinstance(value, bool):
                lines.append(f"{tag} = .{'TRUE' if value else 'FALSE'}.")
            elif isinstance(value, list):
                lines.append(f"{tag} = {' '.join(str(v) for v in value)}")
            elif isinstance(value, float):
                lines.append(f"{tag} = {value}")
            elif isinstance(value, int):
                lines.append(f"{tag} = {value}")
            elif value is not None:
                lines.append(f"{tag} = {value}")
        return "\n".join(lines) + "\n"


class KPOINTSParser:
    """Parse KPOINTS files."""

    @staticmethod
    def parse(content: str) -> dict[str, Any]:
        lines = [l.split("#")[0].strip() for l in content.split("\n")]
        lines = [l for l in lines if l]
        if len(lines) < 4:
            return {"style": "M", "grid": [1, 1, 1], "shift": [0.0, 0.0, 0.0]}
        try:
            grid = [int(x) for x in lines[3].split()[:3]]
        except (ValueError, IndexError):
            grid = [1, 1, 1]
        style_map = {"m": "M", "g": "G", "a": "A", "l": "L"}
        style_char = lines[2].strip().lower() if len(lines) > 2 else "m"
        style = style_map.get(style_char, "M")
        shift = [0.0, 0.0, 0.0]
        if len(lines) > 4 and lines[4].strip().lower().startswith(("t", ".t")):
            try:
                shift = [float(x) for x in lines[4].split()[:3] if x.lower() not in ("t", ".true.", ".t.")]
            except (ValueError, IndexError):
                pass
        return {"style": style, "grid": grid, "shift": shift}

    @staticmethod
    def to_string(params: dict[str, Any]) -> str:
        style = params.get("style", "M")
        grid = params.get("grid", [1, 1, 1])
        shift = params.get("shift", [0.0, 0.0, 0.0])
        lines = [
            "K-Points generated by VASP GUI",
            "0",
            style,
            f"{grid[0]} {grid[1]} {grid[2]}",
            f"{shift[0]} {shift[1]} {shift[2]}",
        ]
        return "\n".join(lines) + "\n"


class POSCARParser:
    """Parse POSCAR files."""

    @staticmethod
    def parse(content: str) -> dict[str, Any]:
        lines = content.split("\n")
        if len(lines) < 7:
            return {"comment": "", "lattice": [[1,0,0],[0,1,0],[0,0,1]], "elements": [], "counts": [], "coords": [], "coord_type": "Direct"}
        comment = lines[0].strip()
        # Parse lattice vectors (lines 2-4)
        lattice = []
        for i in range(2, 5):
            try:
                lattice.append([float(x) for x in lines[i].split()[:3]])
            except (ValueError, IndexError):
                lattice.append([1.0 if j == i-2 else 0.0 for j in range(3)])
        # Elements and counts (lines 5-6)
        try:
            elements = lines[5].split()
            counts = [int(x) for x in lines[6].split()]
        except (ValueError, IndexError):
            elements, counts = [], []
        # Find coordinate start
        coord_type = "Direct"
        coord_start = 7
        # Skip 'Selective dynamics' if present
        if len(lines) > 7 and lines[7].strip().lower().startswith(("s", "select")):
            coord_start = 8
        # Check if current line is a coordinate type marker (starts with letter, no numbers)
        if len(lines) > coord_start:
            test_line = lines[coord_start].strip()
            if test_line and test_line[0].isalpha() and not any(c.isdigit() for c in test_line):
                tlower = test_line.lower()
                coord_type = "Cartesian" if tlower.startswith(("c", "k")) else "Direct"
                coord_start += 1
        # Parse coordinates
        coords = []
        total = sum(counts) if counts else 0
        for i in range(coord_start, min(coord_start + total, len(lines))):
            try:
                coord = [float(x) for x in lines[i].split()[:3]]
                if len(coord) == 3:
                    coords.append(coord)
            except (ValueError, IndexError):
                pass
        return {"comment": comment, "lattice": lattice, "elements": elements,
                "counts": counts, "coords": coords, "coord_type": coord_type}

    @staticmethod
    def to_string(params: dict[str, Any]) -> str:
        lines = [params.get("comment", "Generated by VASP GUI")]
        lines.append("1.0")
        for vec in params.get("lattice", [[1,0,0],[0,1,0],[0,0,1]]):
            lines.append(f"  {vec[0]:.16f}  {vec[1]:.16f}  {vec[2]:.16f}")
        lines.append(" ".join(params.get("elements", [])))
        lines.append(" ".join(str(c) for c in params.get("counts", [])))
        lines.append(params.get("coord_type", "Direct"))
        for c in params.get("coords", []):
            lines.append(f"  {c[0]:.16f}  {c[1]:.16f}  {c[2]:.16f}")
        return "\n".join(lines) + "\n"


class OSZICARParser:
    """Parse OSZICAR energy data."""

    # This matches OSZICAR lines like:
    #   1 T= 300.0 E= -123.456 F= -123.457 E0= -123.456 EK= 1.234 SP= 0.00 SK= 0.00
    # Also handles: "  1 F= -.12345678E+03 E0= -.12345678E+03  d E =-.123456E-03"
    PATTERN = re.compile(
        r'^\s*(?P<step>\d+)\s+'
        r'(?:T=\s*(?P<T>\S+)\s+)?'
        r'(?:E=\s*(?P<E>\S+)\s+)?'
        r'F=\s*(?P<F>\S+)'
        r'(?:\s+E0=\s*(?P<E0>\S+))?'
        r'(?:\s+EK=\s*(?P<EK>\S+))?'
        r'(?:\s+SP=\s*(?P<SP>\S+))?'
        r'(?:\s+SK=\s*(?P<SK>\S+))?',
        re.MULTILINE)

    IONIC_STEP_PATTERN = re.compile(
        r'^\s*-+\s*ion\s+step\s+(\d+)\s*-+', re.IGNORECASE | re.MULTILINE)

    @staticmethod
    def parse(content: str) -> list[dict]:
        steps = []
        prev_e = None
        # Track ionic step boundaries
        ionic_indices = []
        lines = content.split("\n")
        for i, line in enumerate(lines):
            m_ion = OSZICARParser.IONIC_STEP_PATTERN.match(line)
            if m_ion:
                ionic_indices.append({"line": i, "ion_step": int(m_ion.group(1))})

        for m in OSZICARParser.PATTERN.finditer(content):
            # F is required; E may be in the same group or E0
            try:
                energy_str = m.group("E") or m.group("E0") or m.group("F")
                e = float(energy_str)
            except (ValueError, TypeError):
                continue
            delta = e - prev_e if prev_e is not None else 0.0
            prev_e = e
            # Parse optional temperature
            try:
                temp = float(m.group("T")) if m.group("T") else 300.0
            except (ValueError, TypeError):
                temp = 300.0
            # Parse optional free energy
            try:
                f_energy = float(m.group("F")) if m.group("F") else e
            except (ValueError, TypeError):
                f_energy = e
            # Determine which ionic step this belongs to
            pos = m.start()
            line_idx = content[:pos].count("\n")
            current_ionic = 1
            for ib in ionic_indices:
                if ib["line"] <= line_idx:
                    current_ionic = ib["ion_step"]
            steps.append({
                "step": int(m.group("step")),
                "energy": e,
                "free_energy": f_energy,
                "temperature": temp,
                "delta_e": delta,
                "ionic_step": current_ionic,
                "step_type": "electronic"
            })
        return steps

    @staticmethod
    def find_ionic_boundaries(content: str) -> list[dict]:
        """Return ionic step boundary positions and counts."""
        boundaries = []
        for m in OSZICARParser.IONIC_STEP_PATTERN.finditer(content):
            boundaries.append({
                "ion_step": int(m.group(1)),
                "position": m.start(),
            })
        return boundaries


class DOSCARParser:
    """Parse VASP DOSCAR files.

    Format:
      Line 1: NEDOS  E_max(?)  E_Fermi  spare  NIONS  spare  spare
      Lines 2-4: reserved
      Then NEDOS lines of TDOS: energy  dos_up  dos_down  idos_up  idos_down
      Then for each ion: blank line + NEDOS lines of PDOS (columns vary by LORBIT)
    """

    @staticmethod
    def parse(content: str) -> dict:
        lines = content.split("\n")
        if len(lines) < 5:
            return {"nedos": 0, "e_fermi": 0.0, "nions": 0, "tdos": [], "pdos": []}

        # ── Header line ──
        header_parts = lines[0].split()
        nedos = int(header_parts[0]) if len(header_parts) > 0 else 0
        e_fermi = float(header_parts[2]) if len(header_parts) > 2 else 0.0
        nions = int(header_parts[4]) if len(header_parts) > 4 else 0

        # ── TDOS block (starts at line 4, 0-indexed) ──
        tdos_start = 4
        tdos = []
        for i in range(tdos_start, min(tdos_start + nedos, len(lines))):
            parts = lines[i].split()
            if len(parts) < 3:
                continue
            try:
                entry = {
                    "energy": float(parts[0]),
                    "dos_up": float(parts[1]),
                    "dos_down": float(parts[2]) if len(parts) > 2 else 0.0,
                    "idos_up": float(parts[3]) if len(parts) > 3 else 0.0,
                    "idos_down": float(parts[4]) if len(parts) > 4 else 0.0,
                }
                tdos.append(entry)
            except (ValueError, IndexError):
                continue

        # ── PDOS blocks (one per ion) ──
        pdos_start = tdos_start + nedos
        pdos = []
        line_idx = pdos_start

        for _ in range(nions):
            if line_idx >= len(lines):
                break
            # Skip blank/separator line(s)
            while line_idx < len(lines) and not lines[line_idx].strip():
                line_idx += 1
            if line_idx >= len(lines):
                break

            # Read nedos lines of PDOS for this ion
            ion_pdos = []
            for _ in range(nedos):
                if line_idx >= len(lines):
                    break
                parts = lines[line_idx].split()
                if len(parts) >= 3:
                    try:
                        row = {"energy": float(parts[0])}
                        # Determine column layout from count
                        ncols = len(parts) - 1
                        if ncols <= 5:
                            # Non-spin-polarized: s, p, d (3) or s_up,s_down,p_up,p_down,d_up,d_down (6)
                            orbitals = ["s", "p", "d"]
                            for j, orb in enumerate(orbitals):
                                if 1 + j * 2 < len(parts):
                                    row[orb] = float(parts[1 + j * 2])
                                if 1 + j * 2 + 1 < len(parts):
                                    row[f"{orb}_down"] = float(parts[1 + j * 2 + 1])
                        elif ncols == 7:
                            # s, s_down, p, p_down, d, d_down, f (first f column)
                            for j, orb in enumerate(["s", "p", "d", "f"]):
                                idx = 1 + j * 2
                                if idx < len(parts):
                                    row[orb] = float(parts[idx])
                                if idx + 1 < len(parts):
                                    row[f"{orb}_down"] = float(parts[idx + 1])
                        elif ncols >= 9:
                            # s_up, s_down, p_up, p_down, d_up, d_down, f_up, f_down
                            for j, orb in enumerate(["s", "p", "d", "f"]):
                                idx = 1 + j * 2
                                if idx < len(parts):
                                    row[orb] = float(parts[idx])
                                if idx + 1 < len(parts):
                                    row[f"{orb}_down"] = float(parts[idx + 1])
                        else:
                            # Generic: store all columns
                            for j in range(1, len(parts)):
                                row[f"col_{j}"] = float(parts[j])
                        ion_pdos.append(row)
                    except (ValueError, IndexError):
                        pass
                line_idx += 1
            pdos.append(ion_pdos)

        return {
            "nedos": nedos,
            "e_fermi": e_fermi,
            "nions": nions,
            "tdos": tdos,
            "pdos": pdos,
        }


class EIGENVALParser:
    """Parse VASP EIGENVAL files.

    Format:
      Lines 1-4: comment
      Line 5: unknown unknown unknown
      Line 6: n_electrons  n_kpoints  n_bands
      For each k-point:
        blank line
        kx ky kz weight
        For each band: band_index  eigenvalue  occupancy
    """

    @staticmethod
    def parse(content: str) -> dict:
        lines = content.split("\n")
        if len(lines) < 7:
            return {"n_kpoints": 0, "n_bands": 0, "n_electrons": 0,
                    "e_fermi": 0.0, "kpoints": [], "bands": [], "occupancies": []}

        # Line 6 (0-indexed: 5): n_electrons, n_kpoints, n_bands
        try:
            parts6 = lines[5].split()
            n_electrons = int(parts6[0]) if len(parts6) > 0 else 0
            n_kpoints = int(parts6[1]) if len(parts6) > 1 else 0
            n_bands = int(parts6[2]) if len(parts6) > 2 else 0
        except (ValueError, IndexError):
            return {"n_kpoints": 0, "n_bands": 0, "n_electrons": 0,
                    "e_fermi": 0.0, "kpoints": [], "bands": [], "occupancies": []}

        kpoints = []
        bands: list[list[float]] = [[] for _ in range(n_bands)]
        occupancies: list[list[float]] = [[] for _ in range(n_bands)]

        line_idx = 6
        for ikpt in range(n_kpoints):
            # Skip blank line
            while line_idx < len(lines) and not lines[line_idx].strip():
                line_idx += 1
            if line_idx >= len(lines):
                break

            # K-point line
            kp_parts = lines[line_idx].split()
            if len(kp_parts) >= 3:
                try:
                    kpoints.append({
                        "x": float(kp_parts[0]),
                        "y": float(kp_parts[1]),
                        "z": float(kp_parts[2]),
                        "weight": float(kp_parts[3]) if len(kp_parts) > 3 else 0.0,
                        "index": ikpt,
                    })
                except (ValueError, IndexError):
                    kpoints.append({"x": 0, "y": 0, "z": 0, "weight": 0, "index": ikpt})
            else:
                kpoints.append({"x": 0, "y": 0, "z": 0, "weight": 0, "index": ikpt})
            line_idx += 1

            # Band lines
            for ib in range(n_bands):
                if line_idx >= len(lines):
                    break
                parts = lines[line_idx].split()
                if len(parts) >= 2:
                    try:
                        eigenvalue = float(parts[1])
                        occ = float(parts[2]) if len(parts) > 2 else 0.0
                    except (ValueError, IndexError):
                        eigenvalue = 0.0
                        occ = 0.0
                else:
                    eigenvalue = 0.0
                    occ = 0.0
                if ib < n_bands:
                    bands[ib].append(eigenvalue)
                    occupancies[ib].append(occ)
                line_idx += 1

        # Estimate Fermi level: midpoint between highest occupied and lowest unoccupied
        e_fermi = 0.0
        if bands and occupancies:
            all_vals = []
            for ib in range(len(bands)):
                for ik in range(len(bands[ib])):
                    all_vals.append((bands[ib][ik], occupancies[ib][ik]))
            occupied = [e for e, o in all_vals if o > 0.5]
            unoccupied = [e for e, o in all_vals if o <= 0.5]
            if occupied and unoccupied:
                vbm = max(occupied)
                cbm = min(unoccupied)
                e_fermi = (vbm + cbm) / 2.0
            elif occupied:
                e_fermi = max(occupied)

        return {
            "n_kpoints": n_kpoints,
            "n_bands": n_bands,
            "n_electrons": n_electrons,
            "e_fermi": e_fermi,
            "kpoints": kpoints,
            "bands": bands,
            "occupancies": occupancies,
        }


class OUTCARParser:
    """Parse OUTCAR files for key metadata."""

    @staticmethod
    def parse_metadata(content: str) -> dict:
        """Extract system info, energies, forces, timing, convergence."""
        result = {
            "system": "",
            "n_atoms": 0,
            "n_types": 0,
            "volume": 0.0,
            "ionic_steps": [],
            "total_cpu_time": 0.0,
            "converged": False,
            "magnetization": [],
        }

        # System name
        m = re.search(r'POSCAR\s*=\s*(\S+)', content)
        if m:
            result["system"] = m.group(1)

        # Number of atoms / types
        m = re.search(r'ions per type\s*=\s*([\d\s]+)', content)
        if m:
            types = [int(x) for x in m.group(1).split()]
            result["n_types"] = len(types)
            result["n_atoms"] = sum(types)

        # Volume
        m = re.search(r'volume of cell:\s*([\d.]+)', content)
        if m:
            result["volume"] = float(m.group(1))

        # Ionic step energies
        ionic_blocks = re.split(r'-+\s*ion\s+step\s+\d+\s*-+', content)[1:]
        # Also parse using the header pattern
        ion_pattern = re.compile(
            r'-+\s*ion\s+step\s+(\d+)\s*-+\n(.*?)(?=-+\s*ion\s+step|$)',
            re.DOTALL
        )
        for m in ion_pattern.finditer(content):
            ion_num = int(m.group(1))
            block = m.group(2)
            step_info = {"ion_step": ion_num}

            # Energy: look for "FREE ENERGIE OF THE ION-ELECTRON SYSTEM"
            e_m = re.search(r'FREE ENERGIE OF THE ION-ELECTRON SYSTEM\s*\n.*?\n.*?\n\s*[\w-]+\s+[\w-]+\s+([\d.\-E+]+)\s+([\d.\-E+]+)', block)
            if e_m:
                step_info["free_energy"] = float(e_m.group(1))
                step_info["energy0"] = float(e_m.group(2))

            # Convergence check
            if "reached required accuracy" in block.lower():
                step_info["converged"] = True
            else:
                step_info["converged"] = False

            result["ionic_steps"].append(step_info)

        # Overall convergence
        result["converged"] = "reached required accuracy" in content.lower()

        # Total CPU time
        m = re.search(r'Total CPU time used \(sec\):\s*([\d.]+)', content)
        if m:
            result["total_cpu_time"] = float(m.group(1))

        # Magnetization
        mag_pattern = re.compile(r'number of electron\s+([\d.]+)\s+magnetization\s+\(x\)\s+([\d.\-]+)', re.IGNORECASE)
        mags = mag_pattern.findall(content)
        if mags:
            result["magnetization"] = [{"n_electrons": float(m[0]), "mag_x": float(m[1])} for m in mags]

        return result

    @staticmethod
    def extract_final_energy(content: str) -> float | None:
        """Extract final total energy from OUTCAR."""
        energies = re.findall(r'FREE ENERGIE OF THE ION-ELECTRON SYSTEM\s*\n.*?\n.*?\n\s*[\w-]+\s+[\w-]+\s+([\d.\-E+]+)', content)
        if energies:
            return float(energies[-1])
        # Fallback: sigma→0 energy
        sigmas = re.findall(r'energy\(sigma->0\)\s*=\s*([\d.\-E+]+)', content)
        if sigmas:
            return float(sigmas[-1])
        return None

    @staticmethod
    def extract_forces(content: str) -> list[dict]:
        """Extract forces for all atoms at each ionic step."""
        force_pattern = re.compile(
            r'POSITION\s+TOTAL-FORCE\s*\(eV/Angst\)\s*\n\s*-+\s*\n(.*?)(?:\n\s*\n|\n\s*-)',
            re.DOTALL
        )
        all_forces = []
        for m in force_pattern.finditer(content):
            block = m.group(1)
            forces = []
            for line in block.strip().split("\n"):
                parts = line.split()
                if len(parts) >= 6:
                    try:
                        forces.append({
                            "fx": float(parts[3]),
                            "fy": float(parts[4]),
                            "fz": float(parts[5]),
                        })
                    except (ValueError, IndexError):
                        pass
            if forces:
                all_forces.append(forces)
        return all_forces

    @staticmethod
    def extract_dielectric(content: str) -> dict | None:
        """Extract dielectric tensor if LEPSILON=True."""
        # Look for dielectric tensor block
        m = re.search(
            r'MACROSCOPIC STATIC DIELECTRIC TENSOR.*?\n\s*-+\s*\n(.*?)(?:\n\s*\n|\n\s*-)',
            content, re.DOTALL
        )
        if not m:
            return None
        block = m.group(1)
        tensor = []
        for line in block.strip().split("\n"):
            parts = line.split()
            if len(parts) >= 3:
                try:
                    tensor.append([float(x) for x in parts[:3]])
                except ValueError:
                    pass
        if len(tensor) == 3:
            return {
                "xx": tensor[0][0], "xy": tensor[0][1], "xz": tensor[0][2],
                "yx": tensor[1][0], "yy": tensor[1][1], "yz": tensor[1][2],
                "zx": tensor[2][0], "zy": tensor[2][1], "zz": tensor[2][2],
            }
        return None
